apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: fds-risk-model
spec:
  predictor:
    model:
      modelFormat:
        name: mlflow
      storageUri: s3://pay-model-artifacts/fds-risk-model/1
